name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Check approval status
        id: check-approval
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approve
          body: |
            {
              "event": "APPROVE"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag a Release
        if: steps.check-approval.outputs.data != null
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git tag -a v1.0 -m "Release v1.0"
          git push origin --tags

      - name: Deploy to Production
        if: steps.check-approval.outputs.data != null
        run: npx serverless deploy --stage production
